
// This file has been generated by the GUI designer. Do not modify.
namespace sistemacadastrolivros
{
	public partial class ErrorMessageForm
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.Image image62;

		private global::Gtk.Label ErrorMessageLabel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget sistemacadastrolivros.ErrorMessageForm
			this.Name = "sistemacadastrolivros.ErrorMessageForm";
			this.Title = global::Mono.Unix.Catalog.GetString("Ocorreu um problema");
			this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-close", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child sistemacadastrolivros.ErrorMessageForm.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.HeightRequest = 100;
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.image62 = new global::Gtk.Image();
			this.image62.Name = "image62";
			this.image62.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-dialog-error", global::Gtk.IconSize.Menu);
			this.fixed3.Add(this.image62);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.image62]));
			w2.X = 7;
			w2.Y = 14;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.ErrorMessageLabel = new global::Gtk.Label();
			this.ErrorMessageLabel.Name = "ErrorMessageLabel";
			this.ErrorMessageLabel.LabelProp = global::Mono.Unix.Catalog.GetString("label9");
			this.fixed3.Add(this.ErrorMessageLabel);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.ErrorMessageLabel]));
			w3.X = 3;
			w3.Y = 41;
			w1.Add(this.fixed3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1[this.fixed3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Internal child sistemacadastrolivros.ErrorMessageForm.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5[this.buttonOk]));
			w6.Expand = false;
			w6.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 373;
			this.DefaultHeight = 148;
			this.Show();
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
