
// This file has been generated by the GUI designer. Do not modify.
namespace sistemacadastrolivros
{
	public partial class NewItem
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label1;

		private global::Gtk.Entry TitleInput;

		private global::Gtk.Label label2;

		private global::Gtk.Entry AuthorInput;

		private global::Gtk.Label label3;

		private global::Gtk.Entry ISBNInput;

		private global::Gtk.Entry GenreInput;

		private global::Gtk.Label label5;

		private global::Gtk.Entry LanguageInput;

		private global::Gtk.Label label6;

		private global::Gtk.SpinButton PageCount;

		private global::Gtk.Label label4;

		private global::Gtk.Button NewBook;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget sistemacadastrolivros.NewItem
			this.Name = "sistemacadastrolivros.NewItem";
			this.Title = global::Mono.Unix.Catalog.GetString("Edição de Livro");
			this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child sistemacadastrolivros.NewItem.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Título");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w1.X = 15;
			w1.Y = 3;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.TitleInput = new global::Gtk.Entry();
			this.TitleInput.WidthRequest = 375;
			this.TitleInput.CanFocus = true;
			this.TitleInput.Name = "TitleInput";
			this.TitleInput.IsEditable = true;
			this.TitleInput.InvisibleChar = '•';
			this.fixed1.Add(this.TitleInput);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.TitleInput]));
			w2.X = 15;
			w2.Y = 20;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Autor");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w3.X = 15;
			w3.Y = 58;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.AuthorInput = new global::Gtk.Entry();
			this.AuthorInput.WidthRequest = 375;
			this.AuthorInput.CanFocus = true;
			this.AuthorInput.Name = "AuthorInput";
			this.AuthorInput.IsEditable = true;
			this.AuthorInput.InvisibleChar = '•';
			this.fixed1.Add(this.AuthorInput);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.AuthorInput]));
			w4.X = 15;
			w4.Y = 80;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("ISBN");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w5.X = 15;
			w5.Y = 119;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.ISBNInput = new global::Gtk.Entry();
			this.ISBNInput.CanFocus = true;
			this.ISBNInput.Name = "ISBNInput";
			this.ISBNInput.IsEditable = true;
			this.ISBNInput.InvisibleChar = '•';
			this.fixed1.Add(this.ISBNInput);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ISBNInput]));
			w6.X = 15;
			w6.Y = 142;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GenreInput = new global::Gtk.Entry();
			this.GenreInput.CanFocus = true;
			this.GenreInput.Name = "GenreInput";
			this.GenreInput.IsEditable = true;
			this.GenreInput.InvisibleChar = '•';
			this.fixed1.Add(this.GenreInput);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GenreInput]));
			w7.X = 222;
			w7.Y = 143;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Idioma");
			this.fixed1.Add(this.label5);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
			w8.X = 15;
			w8.Y = 181;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.LanguageInput = new global::Gtk.Entry();
			this.LanguageInput.WidthRequest = 100;
			this.LanguageInput.CanFocus = true;
			this.LanguageInput.Name = "LanguageInput";
			this.LanguageInput.IsEditable = true;
			this.LanguageInput.InvisibleChar = '•';
			this.fixed1.Add(this.LanguageInput);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.LanguageInput]));
			w9.X = 15;
			w9.Y = 207;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Número de Páginas");
			this.fixed1.Add(this.label6);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
			w10.X = 132;
			w10.Y = 181;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.PageCount = new global::Gtk.SpinButton(1D, 9999D, 1D);
			this.PageCount.CanFocus = true;
			this.PageCount.Name = "PageCount";
			this.PageCount.Adjustment.PageIncrement = 10D;
			this.PageCount.ClimbRate = 1D;
			this.PageCount.Numeric = true;
			this.PageCount.Value = 1D;
			this.fixed1.Add(this.PageCount);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.PageCount]));
			w11.X = 132;
			w11.Y = 208;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Gênero");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w12.X = 224;
			w12.Y = 119;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.NewBook = new global::Gtk.Button();
			this.NewBook.CanFocus = true;
			this.NewBook.Name = "NewBook";
			this.NewBook.UseUnderline = true;
			this.NewBook.Label = global::Mono.Unix.Catalog.GetString("Cadastrar Livro");
			global::Gtk.Image w13 = new global::Gtk.Image();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-new", global::Gtk.IconSize.Menu);
			this.NewBook.Image = w13;
			this.fixed1.Add(this.NewBook);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.NewBook]));
			w14.X = 244;
			w14.Y = 208;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 405;
			this.DefaultHeight = 265;
			this.Show();
			this.NewBook.Clicked += new global::System.EventHandler(this.OnButton2Clicked);
		}
	}
}
